---
- name: Deploy PackStack Base Contoller
  hosts: openstack-controller
  remote_user: root
  tasks:
     - name: Installing Git
       yum:
         name: git
         state: present

     - name: Add OS Repo
       yum:
         name: https://repos.fedorapeople.org/repos/openstack/openstack-mitaka/rdo-release-mitaka-6.noarch.rpm
         state: present

     - name: Installing PackStack
       yum:
         name: openstack-packstack
         state: present

     - name: Clone openstack-for-pcf
       git:
          repo: https://github.com/pivotal-gss/openstack-for-pcf.git
          dest: /opt/openstack-for-pcf
          clone: yes
          version: dev_branch

     - name: Setting up SSH Keys
       command: cp /opt/openstack-for-pcf/id_rsa* ~/.ssh/
       file:
            path: /root/.ssh/id_rsa*
            mode: 0600


     - name: VM Base Package Installation and Updates
       command: sh /opt/openstack-for-pcf/deploy_packstack_packages.sh

     - name: Provisioning Requirements for OpenStack
       command: sh /opt/openstack-for-pcf/deploy_packstack_provisioning.sh
